version: "2"

services:
  db:
    image: mysql:5.7.22
    container_name: wordpress-docker-db-develop
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - "44221:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    networks:
      - wordpress-docker-network

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress-source-db-develop
    ports:
      - "8766:80"
    restart: always
    volumes: 
      - ./src:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress-docker-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wordpress-phpmyadmin-develop
    depends_on:
      - db
    restart: always
    ports:
      - "8232:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - wordpress-docker-network

volumes:
  db_data:

networks:
    wordpress-docker-network:
        driver: bridge
